name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch: # lets you trigger it manually from the Actions tab too

jobs: 
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            rustytoothpickk/tjpork-app:latest
            rustytoothpickk/tjpork-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max    
