version: '3.8'

services:
  tjpork-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/tjpork.db
      - EmailSettings__SmtpHost=tjpork-mailhog
      - EmailSettings__SmtpPort=1025
      - EmailSettings__FromEmail=orders@tjpork.com
    volumes:
      - tjpork-data:/app/data
    depends_on:
      - tjpork-mailhog
      - tjpork-redis
    restart: unless-stopped

  tjpork-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  tjpork-mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI for viewing outgoing customer & owner emails
    restart: unless-stopped

volumes:
  tjpork-data:
